#!/usr/bin/env node

/**
 * Module dependencies.
 */

var parser = require('koa-bodyparser');
var PORT = process.env.PORT || 3000;
var socket = require('koa-socket');
var route = require('koa-route');
var koa = require('koa');

/**
 * Expose `app`.
 */

exports = app = koa();

/**
 * Use body parser.
 */

app.use(parser());

/**
 * Configure routes.
 */

var routes = require('./lib/routes.js');
app.use(route.post('/api/user/register', routes.register));
app.use(route.post('/api/user/:userId/date', routes.date));
app.use(route.post('/api/user/:userId/like', routes.like));
app.use(route.post('/api/user/:userId/settings', routes.settings));

/**
 * Sockets.
 */

// socket.start(app);
// socket.on('join', function(data) {
//   console.log('join event fired', data);
// });

/**
 * Listen on PORT.
 */

app.listen(PORT);
console.log('listening on port ' + PORT);
